name: py37
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - ipython
  - matplotlib-base
  - multiprocess
  - python=3.7.6
  - scipy=1.4.1
  - pip:
    - jupyter==1.0.0
    - jupyter-client==6.1.6
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - markdown==2.6.8
    - markupsafe==1.1.1
    - notebook==6.0.3
    - numba==0.53.1
    - numpy==1.21.2
